ALTER TABLE `Items` change `Name1` `Name` varchar(255) NOT NULL;
ALTER TABLE `Items` change `Name2` `Item Set Name` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `Items` change `Name3` `Event Name` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `Items` change `Name4` `Comments` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `Items` DROP column `ScaleId`;
ALTER TABLE `Items` DROP column `ScaleFlags`;
ALTER TABLE `Items` DROP column `dmg_min3`;
ALTER TABLE `Items` DROP column `dmg_max3`;
ALTER TABLE `Items` DROP column `dmg_type3`;
ALTER TABLE `Items` DROP column `dmg_min4`;
ALTER TABLE `Items` DROP column `dmg_max4`;
ALTER TABLE `Items` DROP column `dmg_type4`;
ALTER TABLE `Items` DROP column `dmg_min5`;
ALTER TABLE `Items` DROP column `dmg_max5`;
ALTER TABLE `Items` DROP column `dmg_type5`;