// This file was automatically generated by the SVN revision extractor.
// There is no need to modify it.

#ifndef SVN_REVISION_H
#define SVN_REVISION_H

#define BUILD_REVISION 1307
#define BUILD_HOST "BEHEMOTH"
#define BUILD_USER "Thetruecrow"
#define BUILD_TIME __TIME__
#define BUILD_DATE __DATE__

#endif		 // SVN_REVISION_H

