ALTER TABLE `gameobject_names`
	CHANGE COLUMN `spellfocus` `listeddata0` INT(10) NOT NULL DEFAULT '0' AFTER defaultflags,
	CHANGE COLUMN `sound1` `listeddata1` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	CHANGE COLUMN `sound2` `listeddata2` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `sound3` `listeddata3` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `sound4` `listeddata4` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `sound5` `listeddata5` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `sound6` `listeddata6` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	CHANGE COLUMN `sound7` `listeddata7` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `sound8` `listeddata8` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `sound9` `listeddata9` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `unknown1` `listeddata10` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `unknown2` `listeddata11` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `unknown3` `listeddata12` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `unknown4` `listeddata13` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `unknown5` `listeddata14` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `unknown6` `listeddata15` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `unknown7` `listeddata16` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `unknown8` `listeddata17` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `unknown9` `listeddata18` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `unknown10` `listeddata19` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `unknown11` `listeddata20` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `unknown12` `listeddata21` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `unknown13` `listeddata22` INT(10) NOT NULL DEFAULT '0',
	CHANGE COLUMN `unknown14` `listeddata23` INT(10) NOT NULL DEFAULT '0';