
-- Table "creature_proto_vehicle" DDL

CREATE TABLE `creature_proto_vehicle` (
  `vehiclecreatureid` int(30) NOT NULL DEFAULT '1',
  `increasehealthbydriver` int(4) NOT NULL DEFAULT '0',
  `accessoryseat1` int(30) NOT NULL DEFAULT '0',
  `accessoryseat2` int(30) NOT NULL DEFAULT '0',
  `accessoryseat3` int(30) NOT NULL DEFAULT '0',
  `accessoryseat4` int(30) NOT NULL DEFAULT '0',
  `accessoryseat5` int(30) NOT NULL DEFAULT '0',
  `accessoryseat6` int(30) NOT NULL DEFAULT '0',
  `accessoryseat7` int(30) NOT NULL DEFAULT '0',
  `accessoryseat8` int(30) NOT NULL DEFAULT '0',
  `seat1hasspells` int(4) NOT NULL DEFAULT '0',
  `seat2hasspells` int(4) NOT NULL DEFAULT '0',
  `seat3hasspells` int(4) NOT NULL DEFAULT '0',
  `seat4hasspells` int(4) NOT NULL DEFAULT '0',
  `seat5hasspells` int(4) NOT NULL DEFAULT '0',
  `seat6hasspells` int(4) NOT NULL DEFAULT '0',
  `seat7hasspells` int(4) NOT NULL DEFAULT '0',
  `seat8hasspells` int(4) NOT NULL DEFAULT '0',
  `seat1spell1` int(30) NOT NULL DEFAULT '0',
  `seat1spell2` int(30) NOT NULL DEFAULT '0',
  `seat1spell3` int(30) NOT NULL DEFAULT '0',
  `seat1spell4` int(30) NOT NULL DEFAULT '0',
  `seat1spell5` int(30) NOT NULL DEFAULT '0',
  `seat1spell6` int(30) NOT NULL DEFAULT '0',
  `seat2spell1` int(30) NOT NULL DEFAULT '0',
  `seat2spell2` int(30) NOT NULL DEFAULT '0',
  `seat2spell3` int(30) NOT NULL DEFAULT '0',
  `seat2spell4` int(30) NOT NULL DEFAULT '0',
  `seat2spell5` int(30) NOT NULL DEFAULT '0',
  `seat2spell6` int(30) NOT NULL DEFAULT '0',
  `seat3spell1` int(30) NOT NULL DEFAULT '0',
  `seat3spell2` int(30) NOT NULL DEFAULT '0',
  `seat3spell3` int(30) NOT NULL DEFAULT '0',
  `seat3spell4` int(30) NOT NULL DEFAULT '0',
  `seat3spell5` int(30) NOT NULL DEFAULT '0',
  `seat3spell6` int(30) NOT NULL DEFAULT '0',
  `seat4spell1` int(30) NOT NULL DEFAULT '0',
  `seat4spell2` int(30) NOT NULL DEFAULT '0',
  `seat4spell3` int(30) NOT NULL DEFAULT '0',
  `seat4spell4` int(30) NOT NULL DEFAULT '0',
  `seat4spell5` int(30) NOT NULL DEFAULT '0',
  `seat4spell6` int(30) NOT NULL DEFAULT '0',
  `seat5spell1` int(30) NOT NULL DEFAULT '0',
  `seat5spell2` int(30) NOT NULL DEFAULT '0',
  `seat5spell3` int(30) NOT NULL DEFAULT '0',
  `seat5spell4` int(30) NOT NULL DEFAULT '0',
  `seat5spell5` int(30) NOT NULL DEFAULT '0',
  `seat5spell6` int(30) NOT NULL DEFAULT '0',
  `seat6spell1` int(30) NOT NULL DEFAULT '0',
  `seat6spell2` int(30) NOT NULL DEFAULT '0',
  `seat6spell3` int(30) NOT NULL DEFAULT '0',
  `seat6spell4` int(30) NOT NULL DEFAULT '0',
  `seat6spell5` int(30) NOT NULL DEFAULT '0',
  `seat6spell6` int(30) NOT NULL DEFAULT '0',
  `seat7spell1` int(30) NOT NULL DEFAULT '0',
  `seat7spell2` int(30) NOT NULL DEFAULT '0',
  `seat7spell3` int(30) NOT NULL DEFAULT '0',
  `seat7spell4` int(30) NOT NULL DEFAULT '0',
  `seat7spell5` int(30) NOT NULL DEFAULT '0',
  `seat7spell6` int(30) NOT NULL DEFAULT '0',
  `seat8spell1` int(30) NOT NULL DEFAULT '0',
  `seat8spell2` int(30) NOT NULL DEFAULT '0',
  `seat8spell3` int(30) NOT NULL DEFAULT '0',
  `seat8spell4` int(30) NOT NULL DEFAULT '0',
  `seat8spell5` int(30) NOT NULL DEFAULT '0',
  `seat8spell6` int(30) NOT NULL DEFAULT '0',
  PRIMARY KEY (`vehiclecreatureid`),
  UNIQUE KEY `SeatVehicle` (`vehiclecreatureid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
