CREATE TABLE IF NOT EXISTS `creature_staticspawns` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `entry` mediumint(8) NOT NULL,
  `map` smallint(5) NOT NULL,
  `position_x` float NOT NULL,
  `position_y` float NOT NULL,
  `position_z` float NOT NULL,
  `orientation` float NOT NULL,
  `movetype` tinyint(1) NOT NULL DEFAULT '0',
  `displayid` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `faction` smallint(5) NOT NULL DEFAULT '14',
  `flags` int(10) NOT NULL DEFAULT '0',
  `bytes0` int(10) NOT NULL DEFAULT '0',
  `bytes1` int(10) NOT NULL DEFAULT '0',
  `bytes2` int(10) NOT NULL DEFAULT '0',
  `emote_state` int(10) NOT NULL DEFAULT '0',
  `channel_spell` int(10) NOT NULL DEFAULT '0',
  `channel_target_sqlid` int(10) NOT NULL DEFAULT '0',
  `channel_target_sqlid_creature` int(10) NOT NULL DEFAULT '0',
  `standstate` int(10) NOT NULL DEFAULT '0',
  `MountedDisplayID` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `ItemSlot1` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `ItemSlot2` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `ItemSlot3` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `phase` smallint(5) unsigned NOT NULL DEFAULT '1',
  `vehicle` tinyint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Static Spawn System';